name: Cleanup Release Branch

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    permissions:
      contents: write
    
    steps:
      - name: Set up GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Check PRs and delete branch
        run: |
          # Extract branch information
          RELEASE_BRANCH="${{ github.event.pull_request.head.ref }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Release branch: $RELEASE_BRANCH"
          echo "Merged to: $BASE_BRANCH"
          
          # Only delete if branch has been merged to both develop and main
          if [ "$BASE_BRANCH" = "main" ]; then
            # Check if already merged to develop
            DEVELOP_MERGED=$(gh pr list --search "head:$RELEASE_BRANCH base:develop is:closed is:merged" --json number | jq length)
            
            if [ "$DEVELOP_MERGED" -gt 0 ]; then
              echo "Branch has been merged to both develop and main. Deleting..."
              
              # Delete the remote branch
              gh api --method DELETE /repos/${{ github.repository }}/git/refs/heads/$RELEASE_BRANCH
              echo "✅ Release branch $RELEASE_BRANCH deleted."
            else
              echo "⏳ Branch has only been merged to main, not deleting yet."
            fi
          else
            echo "⏳ Branch has only been merged to develop, not deleting yet."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 