name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - production
          - pre-release

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Create release branch
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_BRANCH="release/v$VERSION"
          BASE_BRANCH="main"

          # Get the SHA of the base branch
          SHA=$(gh api /repos/${{ github.repository }}/git/ref/heads/$BASE_BRANCH --jq .object.sha)

          # Create the new branch on the remote repository
          gh api -X POST /repos/${{ github.repository }}/git/refs -f ref="refs/heads/$RELEASE_BRANCH" -f sha=$SHA

          # Create the VERSION.md file locally
          echo "# Release v$VERSION" > VERSION.md
          CONTENT=$(base64 -w 0 VERSION.md)

          # Create the commit on the release branch via API
          gh api -X PUT /repos/${{ github.repository }}/contents/VERSION.md \
            -f message="chore: prepare release v$VERSION" \
            -f content="$CONTENT" \
            -f branch="$RELEASE_BRANCH"
      
      - name: Generate release notes
        id: release_notes
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_DATE=$(date +"%b %d, %Y")
          
          # Find the most recent merge commit
          LAST_MERGE_HASH=$(git log --merges -n 1 --format="%H")
          
          # Create custom release notes
          {
            echo "# Release v$VERSION"
            echo ""
            echo "Commits on $RELEASE_DATE"
            
            # Get all non-merge commits since the last merge
            git log ${LAST_MERGE_HASH}..HEAD --no-merges --format="%s%n%an%n%an%ncommitted%n"
          } > RELEASE_NOTES.txt
          
          cat RELEASE_NOTES.txt
          
          # Save release notes to be used in subsequent steps
          RELEASE_NOTES="$(cat RELEASE_NOTES.txt)"
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Create PRs to develop and master
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_BRANCH="release/v$VERSION"
          RELEASE_TYPE="${{ github.event.inputs.release_type }}"
          
          # Create PR to develop
          gh pr create --base develop --head $RELEASE_BRANCH --title "Merge release v$VERSION into develop" --body "${{ env.RELEASE_NOTES }}"
          
          # Create PR to master with release info in the body
          gh pr create --base master --head $RELEASE_BRANCH --title "Merge release v$VERSION into master" --body "
          # Release v$VERSION
          
          ${{ env.RELEASE_NOTES }}
          
          ---
          
          ## Release Metadata (for automation)
          - release_type: $RELEASE_TYPE
          - version: $VERSION
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}