name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - production
          - pre-release

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Create release branch
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_BRANCH="release/v$VERSION"
          
          # Configure git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Create and switch to the release branch
          git checkout -b $RELEASE_BRANCH
          
          # Create a reference file for the release version
          echo "# Release v$VERSION" > VERSION.md
          git add VERSION.md
          git commit -m "chore: prepare release v$VERSION"
          
          # Push the release branch
          git push origin $RELEASE_BRANCH
      
      - name: Generate custom release notes
        id: release_notes
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_DATE=$(date +"%b %d, %Y")
          
          # Find the most recent merge commit
          LAST_MERGE_HASH=$(git log --merges -n 1 --format="%H")
          
          # Create custom release notes
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "# Release v$VERSION" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "Commits on $RELEASE_DATE" >> $GITHUB_ENV
          
          # Get all non-merge commits since the last merge
          git log ${LAST_MERGE_HASH}..HEAD --no-merges --format="%s%n%an%n%an%ncommitted%n" | grep -v "^$" >> temp_commits.txt
          
          # Add commits to release notes
          cat temp_commits.txt >> $GITHUB_ENV
          
          echo "EOF" >> $GITHUB_ENV
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          generate_release_notes: false
          prerelease: ${{ github.event.inputs.release_type == 'pre-release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create PRs to develop and master
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_BRANCH="release/v$VERSION"
          
          # Create PR to develop
          gh pr create --base develop --head $RELEASE_BRANCH --title "Merge release v$VERSION into develop" --body "${{ env.RELEASE_NOTES }}"
          
          # Create PR to master
          gh pr create --base master --head $RELEASE_BRANCH --title "Merge release v$VERSION into master" --body "${{ env.RELEASE_NOTES }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 