name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - production
          - pre-release

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Create release branch
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_BRANCH="release/v$VERSION"
          
          # Configure git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Create and switch to the release branch
          git checkout -b $RELEASE_BRANCH
          
          # Create a dummy commit for testing
          echo "# Release v$VERSION" >> RELEASE_NOTES.md
          git add RELEASE_NOTES.md
          git commit -m "chore: prepare release v$VERSION"
          
          # Push the release branch
          git push origin $RELEASE_BRANCH
      
      - name: Create tag
        run: |
          VERSION=${{ github.event.inputs.version }}
          TAG="v$VERSION"
          git tag $TAG
          git push origin $TAG
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          generate_release_notes: true
          prerelease: ${{ github.event.inputs.release_type == 'pre-release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create PRs to develop and master
        run: |
          VERSION=${{ github.event.inputs.version }}
          RELEASE_BRANCH="release/v$VERSION"
          
          # GitHub CLI is pre-installed on GitHub-hosted runners
          # Create PR to develop
          gh pr create --base develop --head $RELEASE_BRANCH --title "Merge release v$VERSION into develop" --body "Automated PR to merge release v$VERSION into develop branch"
          
          # Create PR to master
          gh pr create --base master --head $RELEASE_BRANCH --title "Merge release v$VERSION into master" --body "Automated PR to merge release v$VERSION into master branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 