name: Merge Release to Develop

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Find and merge release PR to develop
        run: |
          echo "Searching for release PRs targeting develop branch..."
          
          # List all open PRs in a simple format
          gh pr list --base develop --state open --json number,headRefName,title --template '{{range .}}{{.number}} {{.headRefName}} {{.title}}{{"\n"}}{{end}}' > pr_list.txt
          
          if [ ! -s pr_list.txt ]; then
            echo "No PRs found targeting develop branch"
            exit 0
          fi
          
          echo "Found the following open PRs targeting develop branch:"
          cat pr_list.txt
          
          # Process each PR
          while read PR_NUMBER HEAD_REF PR_TITLE; do
            echo "Checking PR #$PR_NUMBER: $HEAD_REF - $PR_TITLE"
            
            # Only process release PRs
            if [[ "$HEAD_REF" == release/* ]]; then
              echo "Found release PR #$PR_NUMBER with branch $HEAD_REF"
              
              # Get detailed PR info for debugging
              echo "Getting PR details..."
              gh pr view $PR_NUMBER --json mergeable,mergeStateStatus,reviewDecision,baseRefName,headRefName > pr_details.json
              cat pr_details.json
              
              # Check if PR can be merged
              MERGEABLE=$(gh pr view $PR_NUMBER --json mergeable --template "{{.mergeable}}")
              MERGE_STATE=$(gh pr view $PR_NUMBER --json mergeStateStatus --template "{{.mergeStateStatus}}")
              
              echo "PR #$PR_NUMBER mergeable status: $MERGEABLE"
              echo "PR #$PR_NUMBER merge state: $MERGE_STATE"
              
              if [ "$MERGEABLE" != "MERGEABLE" ]; then
                echo "PR #$PR_NUMBER cannot be merged due to mergeable status: $MERGEABLE"
                
                # Try to force merge anyway with --admin flag
                echo "Attempting to force merge with admin privileges..."
                if gh pr merge $PR_NUMBER --admin --merge; then
                  echo "Successfully merged PR #$PR_NUMBER to develop using admin privileges"
                  break
                else
                  echo "Failed to merge PR #$PR_NUMBER even with admin privileges. Skipping."
                  continue
                fi
              fi
              
              # Merge the PR
              echo "Merging PR #$PR_NUMBER to develop normally..."
              if gh pr merge $PR_NUMBER --admin --merge; then
                echo "Successfully merged PR #$PR_NUMBER to develop"
                echo "HEAD_REF=$HEAD_REF" >> $GITHUB_ENV
                break
              else
                echo "Failed to merge PR #$PR_NUMBER. Skipping."
              fi
              
              # Break after first successful merge
              break
            fi
          done < pr_list.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Check if we should clean up the branch
      - name: Check if branch should be cleaned up
        if: env.HEAD_REF != ''
        run: |
          RELEASE_BRANCH="${{ env.HEAD_REF }}"
          echo "Checking if $RELEASE_BRANCH should be cleaned up..."
          
          # Check if the branch has been merged to both develop and main
          DEVELOP_MERGED=$(gh pr list --search "head:$RELEASE_BRANCH base:develop is:closed is:merged" --json number | jq length)
          MAIN_MERGED=$(gh pr list --search "head:$RELEASE_BRANCH base:main is:closed is:merged" --json number | jq length)
          
          echo "Merge status - Develop: $DEVELOP_MERGED, Main: $MAIN_MERGED"
          
          if [ "$DEVELOP_MERGED" -gt 0 ] && [ "$MAIN_MERGED" -gt 0 ]; then
            echo "Branch has been merged to both develop and main. Deleting..."
            gh api --method DELETE /repos/${{ github.repository }}/git/refs/heads/$RELEASE_BRANCH
            echo "✅ Release branch $RELEASE_BRANCH deleted."
          else
            echo "⏳ Branch has not been merged to both branches yet. Skipping cleanup."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 